[package]
name = "graphql"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = { version = "7.0.6", features = ["tokio-sync"] }
async-graphql-poem = "7.0.6"
poem = "3.0.1"
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
